server:
  port: 8084

spring:

  application:
    name: FinancialTransactionManagementService
    version: 1.0.0

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: postgres
    password: projectdb
    url: jdbc:postgresql://localhost:5432/accountdb


app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ
  jwttoken:
    message: 'Login Successful'
