server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: management-service
          uri: lb://MANAGEMENT-SERVICE
          predicates:
            - Path=/transactions/**
          filters:
            - AuthenticationFilter

        - id: authorization-service
          uri: lb://AUTHORIZATION-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/