server:
  port: 8085

spring:

  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

  application:
    name: FinancialTransactionNotificationService
    version: 1.0.0

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: postgres
    password: projectdb
    url: jdbc:postgresql://localhost:5432/notificationdb