server:
  port: 8081
spring:
  application:
    name: MANAGEMENT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: projectdb
    url: jdbc:postgresql://localhost:5432/financialtransactionsdb

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

thisapp:
  app:
    jwtSecret: qwertyuiopASDFGHJKLzxcvbnmQWERTYUIOPqqqqqgVVHGVHGHGVGH
    jwtExpirationMs: 86400000